import Footer from "@/components/Footer";
import Header from "@/components/Header";

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <div className="relative pt-36 md:pt-48 pb-14 mx-auto  px-4 lg:px-8 bg-white text-black">
        <article className="prose prose-slate mx-auto">
          <h1>Privacy Policy</h1>
          <p>Effective date: 17/03/2024</p>
          <h3>1. Introduction</h3>
          <p>
            Welcome to <strong>Clack</strong>.
          </p>
          <p>
            Clack (“us”, “we”, or “our”) operates <a href="https://clack.rkph.me">https://clack.rkph.me</a> (hereinafter
            referred to as “<strong>Service</strong>”).
          </p>
          <p>
            Our Privacy Policy governs your visit to <a href="https://clack.rkph.me">https://clack.rkph.me</a>, and
            explains how we collect, safeguard and disclose information that results from your use of our Service.
          </p>
          <p>
            We use your data to provide and improve Service. By using Service, you agree to the collection and use of
            information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used
            in this Privacy Policy have the same meanings as in our Terms and Conditions.
          </p>
          <p>
            Our Terms and Conditions (“<strong>Terms</strong>”) govern all use of our Service and together with the
            Privacy Policy constitutes your agreement with us (“<strong>agreement</strong>”).
          </p>
          <h3>2. Definitions</h3>
          <p>
            <strong>SERVICE</strong> means the https://clack.rkph.me website operated by Clack.
          </p>
          <p>
            <strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those data
            (or from those and other information either in our possession or likely to come into our possession).
          </p>
          <p>
            <strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service or from
            Service infrastructure itself (for example, the duration of a page visit).
          </p>
          <p>
            <strong>COOKIES</strong> are small files stored on your device (computer or mobile device).
          </p>
          <p>
            <strong>DATA CONTROLLER</strong> means a natural or legal person who (either alone or jointly or in common
            with other persons) determines the purposes for which and the manner in which any personal data are, or are
            to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.
          </p>
          <p>
            <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who processes the
            data on behalf of the Data Controller. We may use the services of various Service Providers in order to
            process your data more effectively.
          </p>
          <p>
            <strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal Data.
          </p>
          <p>
            <strong>THE USER</strong> is the individual using our Service. The User corresponds to the Data Subject, who
            is the subject of Personal Data.
          </p>
          <h3>3. Information Collection and Use</h3>
          <p>
            We collect several different types of information for various purposes to provide and improve our Service to
            you.
          </p>
          <p>
            Clack&#39;s use and transfer of information received from Google APIs to any other app will adhere to{" "}
            <a href="https://developers.google.com/terms/api-services-user-data-policy#additional_requirements_for_specific_api_scopes">
              Google API Services User Data Policy
            </a>
            , including the Limited Use requirements
          </p>
          <p>
            We only ask for personal information when we truly need it to provide a service to you. We collect it by
            fair and lawful means, with your knowledge and consent. We also let you know why we&#39;re collecting it and
            how it will be used.
          </p>
          <p>
            You can sign up with your Google account so your Clack account username will be prefilled with your name and
            your public profile picture.
          </p>
          <p>
            You have the option to &#39;Add Documents&#39; on your Clack page, allowing you to connect Google Docs files
            set to share with a publicly accessible Google Docs URL. Additionally, you can add Notion databases/pages
            that you, the USER, have granted access to through the Clack integration. This enables Clack to access and
            parse document content, compiling word count data to track your writing progress. Please note that this
            information is used exclusively for writing activity tracking features within Clack and is not shared
            externally.
          </p>
          <p>
            By adding a Google Doc and using the writing tracking features, you retain full ownership and rights over
            your intellectual property. Clack does not claim or assume any rights or ownership over the content of the
            documents added or the books you are writing. We access the content solely to provide the writing analytics
            features, with your consent through adding the publicly accessible link.
          </p>
          <p>
            We only retain collected information for as long as necessary to provide you with your requested service.
            What data we store, we&#39;ll protect within commercially acceptable means to prevent loss and theft, as
            well as unauthorized access, disclosure, copying, use or modification.
          </p>
          <p>
            We don&#39;t share any personally identifying information publicly or with third-parties, except when
            required to by Indian law.
          </p>{" "}
          <p>
            We act in the capacity of a data controller and a data processor with regard to the personal data processed
            through Clack and the services in terms of the applicable Indian data protection laws.
          </p>{" "}
          <p>
            Our website may link to external sites that are not operated by us. Please be aware that we have no control
            over the content and practices of these sites, and cannot accept responsibility or liability for their
            respective privacy policies.
          </p>
          <p>
            You are free to refuse our request for your personal information, and your intellectual property
            information, with the understanding that we may be unable to provide you with some of your desired services.
          </p>
          <p>
            Your continued use of our website will be regarded as acceptance of our practices around privacy and
            personal information. If you have any questions about how we handle user data and personal information, feel
            free to contact us.
          </p>
          <h3>4. Types of Data Collected</h3>
          <p>
            <strong>Personal Data</strong>
          </p>
          <p>
            While using our Service, we may ask you to provide us with certain personally identifiable information that
            can be used to contact or identify you (“<strong>Personal Data</strong>”). Personally identifiable
            information may include, but is not limited to:
          </p>
          <ol>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Cookies and Usage Data</li>
          </ol>
          <p>
            We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other
            information that may be of interest to you. You may opt out of receiving any, or all, of these
            communications from us by following the unsubscribe link.
          </p>
          <p>
            <strong>Usage Data</strong>
          </p>
          <p>
            We may also collect information that your browser sends whenever you visit our Service or when you access
            Service by or through a mobile device (“<strong>Usage Data</strong>”).
          </p>
          <p>
            This Usage Data may include information such as your computer&#39;s Internet Protocol address (e.g. IP
            address), browser type, browser version, the pages of our Service that you visit, the time and date of your
            visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p>
            When you access Service with a mobile device, this Usage Data may include information such as the type of
            mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile
            operating system, the type of mobile Internet browser you use, unique device identifiers and other
            diagnostic data.
          </p>
          <p>
            <strong>Tracking Cookies Data</strong>
          </p>
          <p>
            We use cookies and similar tracking technologies to track the activity on our Service and we hold certain
            information.
          </p>
          <p>
            Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are
            sent to your browser from a website and stored on your device. Other tracking technologies are also used
            such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.
          </p>
          <p>
            You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if
            you do not accept cookies, you may not be able to use some portions of our Service.
          </p>
          <p>Examples of Cookies we use:</p>
          <ol>
            <li>
              <strong>Session Cookies:</strong> We use Session Cookies to operate our Service.
            </li>
            <li>
              <strong>Preference Cookies:</strong> We use Preference Cookies to remember your preferences and various
              settings.
            </li>
            <li>
              <strong>Security Cookies:</strong> We use Security Cookies for security purposes.
            </li>
            <li>
              <strong>Advertising Cookies:</strong> Advertising Cookies are used to serve you with advertisements that
              may be relevant to you and your interests.
            </li>
          </ol>
          <h3>5. Use of Data</h3>
          <p>Clack uses the collected data for various purposes:</p>
          <ol>
            <li>to provide and maintain our Service;</li>
            <li>to notify you about changes to our Service;</li>
            <li>to allow you to participate in interactive features of our Service when you choose to do so;</li>
            <li>to provide customer support;</li>
            <li>to gather analysis or valuable information so that we can improve our Service;</li>
            <li>to monitor the usage of our Service;</li>
            <li>to detect, prevent and address technical issues;</li>
            <li>to fulfill any other purpose for which you provide it;</li>
            <li>
              to carry out our obligations and enforce our rights arising from any contracts entered into between you
              and us, including for billing and collection;
            </li>
            <li>
              to provide you with notices about your account and/or subscription, including expiration and renewal
              notices, email-instructions, etc.;
            </li>
            <li>
              to provide you with news, special offers and general information about other goods, services and events
              which we offer that are similar to those that you have already purchased or enquired about unless you have
              opted not to receive such information;
            </li>
            <li>in any other way we may describe when you provide the information;</li>
            <li>for any other purpose with your consent.</li>
          </ol>
          <h3>6. Retention of Data</h3>
          <p>
            We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy
            Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal
            obligations (for example, if we are required to retain your data to comply with applicable laws), resolve
            disputes, and enforce our legal agreements and policies.
          </p>
          <p>
            We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a
            shorter period, except when this data is used to strengthen the security or to improve the functionality of
            our Service, or we are legally obligated to retain this data for longer time periods.
          </p>
          <h3>7. Transfer of Data</h3>
          <p>
            Your information, including Personal Data, may be transferred to – and maintained on – computers located
            outside of your state, province, country or other governmental jurisdiction where the data protection laws
            may differ from those of your jurisdiction.
          </p>
          <p>
            If you are located outside United States and choose to provide information to us, please note that we
            transfer the data, including Personal Data, to United States and process it there.
          </p>
          <p>
            Your consent to this Privacy Policy followed by your submission of such information represents your
            agreement to that transfer.
          </p>
          <p>
            Clack will take all the steps reasonably necessary to ensure that your data is treated securely and in
            accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation
            or a country unless there are adequate controls in place including the security of your data and other
            personal information.
          </p>
          <h3>8. Disclosure of Data</h3>
          <p>We may disclose personal information that we collect, or you provide:</p>
          <ol>
            <li>
              <strong>Disclosure for Law Enforcement.</strong>
            </li>
            <li>
              Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law
              or in response to valid requests by public authorities.
            </li>
            <li>
              <strong>Business Transaction.</strong>
            </li>
            <li>
              If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be
              transferred.
            </li>
            <li>
              <strong>Other cases. We may disclose your information also:</strong>
              <ol>
                <li>to our subsidiaries and affiliates;</li>
                <li>to contractors, service providers, and other third parties we use to support our business;</li>
                <li>to fulfill the purpose for which you provide it;</li>
              </ol>
            </li>
          </ol>
          <h3>9. Security of Data</h3>
          <p>
            The security of your data is important to us but remember that no method of transmission over the Internet
            or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to
            protect your Personal Data, we cannot guarantee its absolute security.
          </p>
          <h3>13. Service Providers</h3>
          <p>
            We may employ third party companies and individuals to facilitate our Service (“{" "}
            <strong>Service Providers</strong>”), provide Service on our behalf, perform Service-related services or
            assist us in analysing how our Service is used.
          </p>
          <p>
            These third parties have access to your Personal Data only to perform these tasks on our behalf and are
            obligated not to disclose or use it for any other purpose.
          </p>
          <h3>14. Analytics</h3>
          <p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>
          <p>
            <strong>Umami Analytics</strong>
          </p>
          <p>
            Umami Analytics is an open-source web analytics tool. You can find their Privacy Policy here:{" "}
            <a href="https://umami.is/privacy">https://umami.is/privacy</a>
          </p>
          <p>
            <strong>PostHog</strong>
          </p>
          <p>
            PostHog is an analytics service and company. You can find their Privacy Policy here:{" "}
            <a href="https://posthog.com/privacy">https://posthog.com/privacy</a>
          </p>
          <h3>15. CI/CD tools</h3>
          <p>We may use third-party Service Providers to automate the development process of our Service.</p>
          <p>
            <strong>GitHub</strong>
          </p>
          <p>GitHub is provided by GitHub, Inc.</p>
          <p>GitHub is a development platform to host and review code, manage projects, and build software.</p>
          <p>
            For more information on what data GitHub collects for what purpose and how the protection of the data is
            ensured, please visit GitHub Privacy Policy page:{" "}
            <a href="https://help.github.com/en/articles/github-privacy-statement">
              https://help.github.com/en/articles/github-privacy-statement
            </a>{" "}
            .
          </p>
          <h3>16. Payments</h3>
          <p>
            We may provide paid products and/or services within Service. In that case, we use third-party services for
            payment processing (e.g. payment processors).
          </p>
          <p>
            We will not store or collect your payment card details. That information is provided directly to our
            third-party payment processors whose use of your personal information is governed by their Privacy Policy.
            These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards
            Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS
            requirements help ensure the secure handling of payment information.
          </p>
          <p>The payment processors we work with are:</p>
          <p>
            <strong>Stripe:</strong>
          </p>
          <p>
            Their Privacy Policy can be viewed at:{" "}
            <a href="https://stripe.com/us/privacy">https://stripe.com/us/privacy</a>
          </p>
          <h3>17. Links to Other Sites</h3>
          <p>
            Our Service may contain links to other sites that are not operated by us. If you click a third party link,
            you will be directed to that third party&#39;s site. We strongly advise you to review the Privacy Policy of
            every site you visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the content, privacy policies or practices of any
            third party sites or services.
          </p>
          <h3>18. Children&#39;s Privacy</h3>
          <p>
            Our Services are not intended for use by children under the age of 18 (“ <strong>Child</strong>” or “
            <strong>Children</strong>”).
          </p>
          <p>
            We do not knowingly collect personally identifiable information from Children under 18. If you become aware
            that a Child has provided us with Personal Data, please contact us. If we become aware that we have
            collected Personal Data from Children without verification of parental consent, we take steps to remove that
            information from our servers.
          </p>
          <h3>19. Changes to This Privacy Policy</h3>
          <p>
            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new
            Privacy Policy on this page.
          </p>
          <p>
            We will let you know via email and/or a prominent notice on our Service, prior to the change becoming
            effective and update “effective date” at the top of this Privacy Policy.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
            are effective when they are posted on this page.
          </p>
          <h3>20. Contact Us</h3>
          <p>If you have any questions about this Privacy Policy, please contact us:</p>
          <p>By email: support@clack.rkph.me.</p>
          <p>Last updated: 17/03/2024</p>
        </article>
      </div>
      <Footer />
    </>
  );
}
